/**
 * Runtime backend selection. The Node/MySQL API preserves the PostgREST and
 * Edge Function call shapes used by the existing React UI.
 */
export type BackendTarget = "supabase" | "node";
const FALLBACK_SUPABASE_URL = "https://kozdctbbvrnyddlftmvf.supabase.co";

const yes = (value: unknown) => String(value ?? "").trim().toLowerCase() === "yes";

export function backendTarget(): BackendTarget {
  const mysqlEnabled = yes(import.meta.env.VITE_USE_MYSQL ?? import.meta.env.VITE_USE_AWS ?? "no");
  const supabaseEnabled = yes(import.meta.env.VITE_USE_SUPABASE ?? (mysqlEnabled ? "no" : "yes"));
  if (mysqlEnabled) return "node";
  if (supabaseEnabled) return "supabase";
  throw new Error("No backend is enabled. Set VITE_USE_MYSQL=yes or VITE_USE_SUPABASE=yes.");
}

export function isNodeBackendEnabled() {
  return backendTarget() === "node";
}

export function apiBaseUrl() {
  const value = String(import.meta.env.VITE_API_URL || import.meta.env.VITE_AWS_API_URL || "").replace(/\/$/, "");
  if (!value) throw new Error("VITE_API_URL is required when VITE_USE_MYSQL=yes.");
  return value;
}

export function functionUrl(name: string) {
  if (backendTarget() === "node") return `${apiBaseUrl()}/v1/functions/${encodeURIComponent(name)}`;
  return `${String(import.meta.env.VITE_SUPABASE_URL || FALLBACK_SUPABASE_URL).replace(/\/$/, "")}/functions/v1/${encodeURIComponent(name)}`;
}

export function restUrl(path: string) {
  const clean = path.replace(/^\//, "");
  if (backendTarget() === "node") return `${apiBaseUrl()}/v1/rest/${clean}`;
  return `${String(import.meta.env.VITE_SUPABASE_URL || FALLBACK_SUPABASE_URL).replace(/\/$/, "")}/rest/v1/${clean}`;
}

/** Route PostgREST traffic generated by supabase-js through Node/MySQL. */
export function backendFetch(input: RequestInfo | URL, init?: RequestInit) {
  if (backendTarget() !== "node") return fetch(input, init);
  const original = typeof input === "string" ? input : input instanceof URL ? input.toString() : input.url;
  const url = new URL(original);
  if (url.pathname.startsWith("/rest/v1/")) {
    const rewritten = `${apiBaseUrl()}/v1/rest/${url.pathname.slice("/rest/v1/".length)}${url.search}`;
    if (typeof Request !== "undefined" && input instanceof Request && !init) return fetch(new Request(rewritten, input));
    return fetch(rewritten, init);
  }
  return fetch(input, init);
}

export async function invokeNodeFunction<T = unknown>(name: string, options: { body?: unknown; headers?: HeadersInit; method?: string } = {}) {
  try {
    const headers = new Headers(options.headers);
    if (options.body !== undefined && !headers.has('content-type')) headers.set('content-type', 'application/json');
    const response = await fetch(functionUrl(name), {
      method: options.method || "POST",
      headers,
      body: options.body === undefined ? undefined : JSON.stringify(options.body),
    });
    const data = await response.json().catch(() => null) as T | null;
    if (!response.ok) return { data: null, error: new Error((data as { error?: string; message?: string } | null)?.error || (data as { message?: string } | null)?.message || `Node API returned ${response.status}`) };
    return { data, error: null };
  } catch (cause) {
    return { data: null, error: cause instanceof Error ? cause : new Error("Node API request failed") };
  }
}
