/**
 * AUTO-GENERATED by scripts/prepare-upgrad-iit-iim-certificates-4k.mjs.
 * Source artwork is restricted to the audited upGrad media manifest.
 */
export type UpgradProgramCertificateMedia = Readonly<{
  certificateImage: string;
  sourceUrl: string;
  sourceWidth: number;
  sourceHeight: number;
  width: number;
  height: number;
  sha256: string;
}>;

export const UPGRAD_PROGRAM_CERTIFICATE_MEDIA = 
{
  "executive-post-graduate-certificate-in-ai-native-software-engineering-iit-kharagpur-iit-kharagpur": {
    "certificateImage": "/assets/programs/iit-iim/certificates/certificate-5487287596d6b9b3c5ef.webp",
    "sourceUrl": "https://d2o2utebsixu4k.cloudfront.net/AI_Native_Cert_1774594404108_40460c17c3dc6c45%20(1)-1553f4c177914099a7176bd40c86d12b.webp",
    "sourceWidth": 960,
    "sourceHeight": 678,
    "width": 3840,
    "height": 2712,
    "sha256": "5487287596d6b9b3c5ef3ab7da30310d69015963534353c59f81d01431ddb4a6"
  },
  "executive-post-graduate-certificate-in-building-ai-products-systems-and-services-iit-kharagpur-iit-kharagpur": {
    "certificateImage": "/assets/programs/iit-iim/certificates/certificate-f36af51e71ae6e7dae8e.webp",
    "sourceUrl": "https://d2o2utebsixu4k.cloudfront.net/Certificate_Image_-_1_1779864837895_5387eea0b1bb042f%20(1)-f1d4c79774234e0d9554081dfee63491.png",
    "sourceWidth": 620,
    "sourceHeight": 469,
    "width": 3840,
    "height": 2905,
    "sha256": "f36af51e71ae6e7dae8e5d15ca3c96a4785f45d6774363b5aebc171bbc9db9db"
  },
  "executive-post-graduate-programme-in-applied-ai-and-agentic-ai-iiit-bangalore": {
    "certificateImage": "/assets/programs/iit-iim/certificates/certificate-3dc70413157229d0ddc8.webp",
    "sourceUrl": "https://d2o2utebsixu4k.cloudfront.net/agentic%20ai%20cer-100kb-e2b350f5cb0e4de290ff5f25a6dad9e3.jpg",
    "sourceWidth": 1500,
    "sourceHeight": 1048,
    "width": 3840,
    "height": 2683,
    "sha256": "3dc70413157229d0ddc8f4d5e538c25005d30d9574893e0ed145ae8b402540fd"
  },
  "executive-programme-in-generative-ai-and-agentic-ai-for-leaders-iiit-bangalore": {
    "certificateImage": "/assets/programs/iit-iim/certificates/certificate-97dc8847780909955b73.webp",
    "sourceUrl": "https://d2o2utebsixu4k.cloudfront.net/Gen%20AI%20Fr%20leaders%20new_11zon-100kb-f2611c7816574f1eb7d496f276f526a6.jpg",
    "sourceWidth": 1500,
    "sourceHeight": 1061,
    "width": 3840,
    "height": 2716,
    "sha256": "97dc8847780909955b73f42f21a1b919a52b426bca9ca0e60bd6a09a5d15400b"
  },
  "mba-from-ljmu-with-iim-udaipur-certification-liverpool-john-moores-university": {
    "certificateImage": "/assets/programs/iit-iim/certificates/certificate-88081e1c9161f6be2388.webp",
    "sourceUrl": "https://d2o2utebsixu4k.cloudfront.net/Certificate%20of%20completion%20layout%201-ca8929459a6f4f4b93b96f6db190933f.webp",
    "sourceWidth": 1492,
    "sourceHeight": 1054,
    "width": 3840,
    "height": 2713,
    "sha256": "88081e1c9161f6be238852a03540cbb75e5bfed4bc0ca5ddf164f72601d97356"
  },
  "professional-certificate-programme-in-ai-for-business-professionals-iim-kozhikode": {
    "certificateImage": "/assets/programs/iit-iim/certificates/certificate-51d6adbaa6a54925391f.webp",
    "sourceUrl": "https://d2o2utebsixu4k.cloudfront.net/PCP_AIB%20CERTTTT-65a7f697f7574ac4b3753192375ed5b4.webp",
    "sourceWidth": 1273,
    "sourceHeight": 900,
    "width": 3840,
    "height": 2715,
    "sha256": "51d6adbaa6a54925391fc1c582a2aa823406aca710a2e3deb70f56f5998da562"
  },
  "professional-certificate-programme-in-data-science-and-agentic-ai-iiit-bangalore": {
    "certificateImage": "/assets/programs/iit-iim/certificates/certificate-5288c96a7cbbc443e67b.webp",
    "sourceUrl": "https://d2o2utebsixu4k.cloudfront.net/PC-100kb-efe078bc54cc4dbc9c7507ecdb004856.jpg",
    "sourceWidth": 1500,
    "sourceHeight": 1050,
    "width": 3840,
    "height": 2688,
    "sha256": "5288c96a7cbbc443e67b40e0cdcc22e7e82bdc7c52d0f7fbe091c635666e6e0a"
  }
} as const satisfies Readonly<Record<string, UpgradProgramCertificateMedia>>;
