from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, KeepTogether
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from reportlab.lib.colors import HexColor
from pathlib import Path

OUT = Path("output/pdf/dekhocampus-content-quality-playbook-2026.pdf")
OUT.parent.mkdir(parents=True, exist_ok=True)

NAVY = HexColor("#16243A")
BLUE = HexColor("#2463D4")
ORANGE = HexColor("#F17829")
MUTED = HexColor("#5E6A7D")
PALE = HexColor("#F3F6FB")
GREEN = HexColor("#0B7A5A")

styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name="CoverTitle", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=27, leading=32, textColor=NAVY, alignment=TA_CENTER, spaceAfter=12))
styles.add(ParagraphStyle(name="CoverSub", parent=styles["Normal"], fontName="Helvetica", fontSize=12, leading=18, textColor=MUTED, alignment=TA_CENTER, spaceAfter=8))
styles.add(ParagraphStyle(name="H1x", parent=styles["Heading1"], fontName="Helvetica-Bold", fontSize=18, leading=23, textColor=NAVY, spaceBefore=12, spaceAfter=8, keepWithNext=1))
styles.add(ParagraphStyle(name="H2x", parent=styles["Heading2"], fontName="Helvetica-Bold", fontSize=13, leading=17, textColor=BLUE, spaceBefore=10, spaceAfter=5, keepWithNext=1))
styles.add(ParagraphStyle(name="H3x", parent=styles["Heading3"], fontName="Helvetica-Bold", fontSize=10.5, leading=14, textColor=NAVY, spaceBefore=7, spaceAfter=3, keepWithNext=1))
styles.add(ParagraphStyle(name="Bodyx", parent=styles["BodyText"], fontName="Helvetica", fontSize=9.2, leading=14, textColor=NAVY, spaceAfter=6))
styles.add(ParagraphStyle(name="Smallx", parent=styles["BodyText"], fontName="Helvetica", fontSize=8, leading=11, textColor=MUTED, spaceAfter=4))
styles.add(ParagraphStyle(name="Bulletx", parent=styles["BodyText"], fontName="Helvetica", fontSize=9, leading=13, leftIndent=13, firstLineIndent=-8, bulletIndent=2, textColor=NAVY, spaceAfter=3))
styles.add(ParagraphStyle(name="Callout", parent=styles["BodyText"], fontName="Helvetica-Bold", fontSize=9.2, leading=14, textColor=GREEN, backColor=HexColor("#EAF8F2"), borderColor=HexColor("#B8E3D0"), borderWidth=0.5, borderPadding=8, spaceBefore=6, spaceAfter=8))
styles.add(ParagraphStyle(name="Codex", parent=styles["BodyText"], fontName="Courier", fontSize=7.6, leading=10, textColor=NAVY, backColor=PALE, borderPadding=6, spaceBefore=3, spaceAfter=6))

def P(text, style="Bodyx"):
    return Paragraph(text, styles[style])

def H(text, level=1):
    return Paragraph(text, styles[{1: "H1x", 2: "H2x", 3: "H3x"}[level]])

def bullets(items):
    return KeepTogether([Paragraph(f"- {item}", styles["Bulletx"]) for item in items])

def table(rows, widths=None, header=True):
    t = Table([[Paragraph(str(c), styles["Smallx"]) for c in row] for row in rows], colWidths=widths, repeatRows=1 if header else 0, hAlign="LEFT")
    commands = [
        ("GRID", (0, 0), (-1, -1), 0.35, HexColor("#D7DFEC")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]
    if header:
        commands += [("BACKGROUND", (0, 0), (-1, 0), NAVY), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white)]
    for row in range(1 if header else 0, len(rows), 2):
        commands.append(("BACKGROUND", (0, row), (-1, row), PALE))
    t.setStyle(TableStyle(commands))
    return t

def header_footer(canvas, doc):
    canvas.saveState()
    width, height = A4
    if doc.page > 1:
        canvas.setStrokeColor(HexColor("#D7DFEC"))
        canvas.line(18 * mm, height - 15 * mm, width - 18 * mm, height - 15 * mm)
        canvas.setFont("Helvetica-Bold", 8)
        canvas.setFillColor(NAVY)
        canvas.drawString(18 * mm, height - 11 * mm, "DekhoCampus Content Quality Playbook")
    canvas.setStrokeColor(HexColor("#D7DFEC"))
    canvas.line(18 * mm, 14 * mm, width - 18 * mm, 14 * mm)
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(MUTED)
    canvas.drawString(18 * mm, 9 * mm, "Internal implementation guide | Reviewed 23 September 2026")
    canvas.drawRightString(width - 18 * mm, 9 * mm, f"Page {doc.page}")
    canvas.restoreState()

story = []
story += [Spacer(1, 30 * mm), P("DEKHOCAMPUS", "CoverSub"), P("Content Quality, SEO and GEO Playbook", "CoverTitle"), P("Reusable rules for exam, course and college pages", "CoverSub"), Spacer(1, 8 * mm)]
story += [P("Purpose: make every education page accurate, useful, human, search-friendly and safe to publish. This document describes the current implementation contract, not a promise of a guaranteed ranking or detector score.", "Callout"), Spacer(1, 18 * mm), P("Version 1.1 | FAQ isolation and current exam workflow", "CoverSub"), PageBreak()]

story += [H("1. Editorial north star"), P("The audience is Indian students and parents. Content must answer the immediate decision in plain English or Indian English, show what is known and unknown, and help a reader take the next safe step. We optimise for search visibility, answer extraction and trust together; no single score replaces editorial judgement."), table([["Dimension", "Implementation rule"], ["Audience", "Students, parents and working applicants in India; explain unfamiliar terms without talking down."], ["Tone", "Clear, practical, calm and trustworthy. Use active voice, contractions and occasional natural Indian context."], ["Goals", "SEO, AEO, GEO, LLMO, E-E-A-T, conversion clarity and low-friction decision support."], ["Accuracy", "Official authority first. Unpublished dates remain pending. Uncertainty is visible, never hidden."], ["Model", "GPT-6 Luna handles research analysis, novelty checks and independent review. GPT-6 Sol writes and revises by default; GPT-5.5 and GPT-5.4 mini remain optional writing alternatives. Validators and human review remain mandatory."]], [34 * mm, 138 * mm]), H("Non-negotiable", 2), P("Never trade accuracy for a fuller-looking page. A transparent 'not announced' value is higher quality than a guessed date, fee, rank or eligibility rule.", "Callout")]

story += [H("2. Inputs required for every page"), bullets(["Primary keyword and natural variants.", "Secondary keywords and related entities.", "Target audience and decision stage.", "Search intent: informational, commercial or transactional.", "Target word count, category and site scope.", "Research signals with source, date checked and confidence.", "Internal-link context and the canonical route.", "For courses and colleges: official institution, campus, programme, intake, approvals, fees and admission route."]), H("Minimum research packet", 2), P("Use no more than six research signals per article. Prefer the conducting authority, government body, university or regulator. Keep research sources private unless a citation is deliberately published and verified.")]

story += [H("3. Research and freshness rules"), table([["Rule", "How it is enforced"], ["Official-first", "Authority and government pages outrank coaching sites, aggregators, social posts and search snippets."], ["Date discipline", "Record checked_at and data_last_checked_at. Do not convert expected dates into facts."], ["2027 handling", "Use published 2027 dates where an authority has issued them. Otherwise show 'not announced' and link to the official notice page."], ["Claim control", "Omit unverifiable claims. Mark changing fees, seats, cut-offs and schedules as subject to official confirmation."], ["Private research", "Research URLs can remain in data_source_urls; they are not automatically shown as public citations."], ["Duplicate control", "Resolve canonical exam/course/college IDs before rewriting. Keep sessions as related schedules, not new exams, unless the authority treats them as separate products."]], [35 * mm, 137 * mm]), P("Current batch example: MICA's official admissions page publishes a 2027 calendar, so those dates are retained; for most other Batch 5 authorities, 2027 schedules were still pending at the checked time.", "Callout")]

story += [H("4. Writing contract"), H("Answer first", 2), bullets(["Answer the search intent directly in the first two or three sentences, but never begin with prompt residue such as 'Answer first:', 'Answer:', 'Executive summary:' or 'Here is the answer:'.", "Avoid generic openings such as 'In today's fast-paced digital world'.", "Put the most decision-relevant fact before background context."]), H("Information gain", 2), bullets(["Add specific facts, practical examples, process steps and realistic trade-offs.", "Use at least one useful comparison, summary table or decision checklist.", "Explain what happens next after the exam, application or counselling step.", "When private evidence supports it, include named authorities, subject codes, paper sections, dates, fee rules or realistic student scenarios. Never invent a gritty detail."]), H("Human rhythm", 2), bullets(["Vary sentence length and paragraph shape.", "Use active voice, contractions and direct transitions.", "Keep paragraphs short enough for mobile reading.", "Use natural Indian context sparingly; do not force Hinglish or slang.", "Do not force a fixed Executive summary -> Key facts -> Conceptual rationale -> Step-by-step guide -> Risk matrix -> Red flags -> FAQs sequence; choose a topic-native outline.", "Never paste table labels and cells as a plain-text stack. Use semantic HTML tables only when a table clarifies a decision; otherwise use bullets or descriptive paragraphs.", "Avoid one uniform didactic voice and consolidate repeated official-verification advice instead of restating the same hedge under every heading.", "Do not invent personal experience, credentials, quotes or testimonials."]), H("Blocked language", 2), P("The following are forbidden: delve, testament, tapestry, paramount, in conclusion, furthermore, moreover, game-changer, dive in, unlock the power, in today's world, beacon, vital role, firstly, secondly, in summary, landscape, seamless, robust, comprehensive and crucial. Em dashes and en dashes are removed.")]

story += [H("5. SEO, AEO, GEO and LLMO implementation"), table([["Layer", "Implementation"], ["On-page SEO", "Keyword in title, first 100 words, one or two H2 headings and three to five natural body mentions. Never stuff."], ["SERP scannability", "Use logical H2/H3 headings, bullets, short paragraphs and a structured table only when it genuinely clarifies a comparison."], ["AEO", "Write direct definitions, date/status answers and eligibility summaries that can stand alone as passages. Store FAQs separately and render them in the dedicated FAQ section."], ["GEO / LLMO", "Use clear entities, authority names, precise claims, source dates and quotable answer blocks. Avoid vague superlatives."], ["Internal links", "At least three to four verified DekhoCampus links: exam hub, category hub, course hub and college hub where relevant."], ["External links", "One official apply link and one official notification or source link. Do not send users to unverified lead forms."], ["Canonical/indexing", "Preserve existing slugs, set one canonical URL, avoid duplicate session pages, update sitemap and redirects when records merge."], ["Schema", "Use only valid, current schema types. Do not add HowTo schema. Treat FAQ schema as an AI readability aid, not a guaranteed Google rich result."], ["Performance", "Use responsive images, explicit dimensions, lazy loading below the fold and Core Web Vitals with INP, LCP and CLS."], ["Accessibility", "Descriptive alt text, labelled controls, keyboard access, readable contrast and no information conveyed by colour alone."]], [35 * mm, 137 * mm])]

story += [H("6. Metadata and output contract"), bullets(["Meta title: keyword frontloaded, maximum 60 characters.", "Meta description: clear benefit and action, maximum 155 characters.", "Title, slug, description, keywords, tags, category and hero_hook must be complete.", "Article HTML must not contain H1 because the page shell supplies H1.", "Each article contains four to eight distinct FAQs in the dedicated FAQ field only. Do not repeat FAQ headings, questions or answers inside article HTML.", "Internal links must point only to verified DekhoCampus paths.", "External links must be separated into apply and official notification/source purposes."]), table([["Required output field", "Purpose"], ["title / slug", "Stable page identity and route."], ["description", "Search and page-summary context."], ["article_html", "Clean H2/H3 body without a duplicate H1 or embedded FAQ block."], ["meta_title / meta_description", "Search snippets within hard length limits."], ["meta_keywords / tags / category", "Discovery and editorial classification."], ["hero_hook", "Matches the title and above-the-fold promise."], ["faqs", "Four to eight distinct question-answer pairs rendered by the dedicated FAQ section."], ["data_source_urls / data_verified_at", "Audit trail and freshness."], ["internal_links / external_links", "Navigation, authority and conversion paths."]], [45 * mm, 127 * mm])]

story += [H("7. Exam page implementation"), bullets(["Show exam name, authority, level, mode, frequency and current status.", "Use a date table with notification, application window, exam and result/counselling rows.", "Separate eligibility, syllabus, pattern, application, preparation and next steps.", "Explain that a score or rank is not an admission offer.", "For recruitment exams, use recruitment language: vacancy notice, tiers, skill test, document verification and joining.", "For medical, law and regulated programmes, defer to the current regulator or authority bulletin.", "When an exam has sessions, link the session schedule from the canonical exam page instead of creating duplicate intent pages.", "Keep a human-readable change log when dates, fees, pattern or authority change."]), H("Exam quality gate", 2), P("A record is publishable only when its identity is resolved, source URLs are official, metadata passes length checks, internal and external links are present, forbidden phrases are absent, FAQs are distinct, and no date is presented without source support.", "Callout")]

story += [H("8. Course page implementation"), bullets(["Start with programme name, awarding institution, degree or certificate, mode, duration and intake.", "Verify eligibility, application route, fee, payment schedule, refund rules and any financing claim from the provider.", "Separate official fee from estimated living cost, optional add-ons and promotional discounts.", "Explain curriculum, delivery format, assessment, mentorship, projects and certificate or degree wording without exaggeration.", "For placement claims, show reporting year, cohort, methodology and source. Never imply a guaranteed job or salary.", "Add a decision table: who it suits, entry requirement, time commitment, cost, recognition and alternatives.", "Use verified course-to-college, course-to-exam and course-to-career internal links.", "Mark partner, franchise, online and executive formats clearly so users do not confuse them with a full-time degree."]), H("Course safety", 2), P("Do not copy competitor pages or imply affiliation. Do not claim UGC, AICTE, approval, accreditation or recognition unless the current official document supports the exact programme and campus.", "Callout")]

story += [H("9. College page implementation"), bullets(["Use official institution name, campus, location, ownership, approvals and accreditation status.", "List admissions routes and link the relevant official exam or counselling page.", "Keep courses, fees, hostel, facilities, scholarships and placement data scoped to the campus and reporting year.", "Distinguish official placement reports from marketing claims, student reviews and third-party estimates.", "Use state, city and college-type links to support discovery without creating thin doorway pages.", "Add an evidence block with source, publication date and last verification date.", "Show contact and application details only when verified; never publish personal credentials or unverified counsellor numbers."]), H("College comparison", 2), P("Comparisons must use the same year, campus and metric. Explain missing data instead of ranking institutions from incompatible sources.")]

story += [H("10. Interlinking architecture"), table([["Page type", "Link to", "Reason"], ["Exam", "Exam hub, category hub, courses, colleges", "Move from intent to options and admission context."], ["Course", "Course hub, related exams, colleges offering it, careers", "Connect research, eligibility and choice."], ["College", "State/city hub, courses, exams, scholarships", "Support local discovery and next actions."], ["Blog", "Relevant exam, course, college and tool pages", "Pass topical context and help users act."], ["Tool", "Exam, course, college and guide pages", "Turn a calculation or checklist into a verified decision path."]], [35 * mm, 65 * mm, 72 * mm]), P("Use descriptive anchor text, keep links contextually useful, avoid repeated exact-match anchors and check every path before publication.")]

story += [H("11. Validation and rejection rules"), table([["Check", "Reject or regenerate when"], ["Metadata", "Title exceeds 60 characters, description exceeds 155, or the promise does not match the article."], ["Structure", "Missing answer-first opening, useful H2/H3 structure, suitable lists or required sections."], ["FAQs", "Fewer than four, duplicated questions, or any FAQ heading, question or answer is repeated inside article HTML."], ["Links", "Missing four internal links, missing official apply link, broken path or unverified external destination."], ["Accuracy", "Fabricated dates, prices, ranks, eligibility, approvals, quotes, testimonials or urgency."], ["Language", "Forbidden phrase, repetitive template, excessive hype, fake first-hand experience or forced Hinglish."], ["Novelty", "Duplicate content, copied competitor wording or a session page competing with the canonical page."], ["Technical", "Invalid HTML, flattened Markdown table, duplicate H1, missing alt text, missing canonical or sitemap regression."], ["Editorial", "Reader cannot tell what is confirmed, pending, estimated or subject to change."]], [35 * mm, 137 * mm]), H("Score policy", 2), P("A structural SEO score can be measured, but a guaranteed 100 score, Grammarly score, QuillBot score or AI-detector result cannot be promised. We use deterministic checks plus human review; external tools are diagnostic, not publication authority.", "Callout")]

story += [H("12. Publication pipeline"), table([["Stage", "Implementation output"], ["1. Select", "Choose next unique record; exclude confirmed duplicates and related sessions."], ["2. Research", "Collect up to six official signals and store source URLs and checked time."], ["3. Normalize", "Resolve canonical ID, slug, authority, category and current status."], ["4. Generate", "Write answer-first content, metadata, FAQs, tables and contextual links."], ["5. Validate", "Run metadata, forbidden phrase, link, FAQ, duplicate and claim checks."], ["6. Review", "Human editor verifies dates, fees, approvals, programme scope and tone."], ["7. Stage", "Import to local database or preview environment; inspect mobile and desktop."], ["8. Publish", "Update canonical, sitemap, redirects, schema and cache together."], ["9. Monitor", "Review authority changes, traffic, search queries, broken links and user feedback."]], [28 * mm, 144 * mm]), H("Rollback rule", 2), P("Every batch is a reviewable artifact. Keep the previous JSON/database backup, preserve canonical slugs and make changes reversible. Never hard-delete a record before references and redirects are checked.")]

story += [H("13. Image and media rules"), bullets(["Use approved local templates or licensed/official assets; do not scrape competitor artwork or logos without rights.", "Keep raw artwork free of text, logos, cards and borders when text is rendered by the UI.", "Use descriptive alt text that explains the image's purpose, not keyword stuffing.", "Store responsive formats and explicit width/height to reduce CLS.", "Lazy-load below-the-fold images and prioritise the hero only when it is the LCP element.", "Keep a source and rights note for institution logos, campus photos and programme images."])]

story += [H("14. Governance checklist before publish"), bullets(["Official source opened and checked at the recorded time.", "All changing values carry a source or pending status.", "No personal data, passwords, private research notes or hidden prompt text appears in public content.", "No promise of admission, selection, employment, salary or guaranteed rank.", "No competitor promotion or copied attribution.", "Canonical URL, sitemap, redirects and internal links are ready.", "Mobile layout, keyboard focus, contrast and link destinations are checked.", "Human editor signs off the batch; rejection reasons are recorded for regeneration."]), H("One-line rule", 2), P("If a student could lose time, money or an opportunity because of the claim, verify it twice and show the source.", "Callout")]

story += [PageBreak(), H("Appendix A. Batch 5 source posture"), P("Batch 5 contains AEEE, CG Pre MCA, CULEE, GEEE, GITAM GAT, Haryana LEET, MICAT, NMAT, OJEE and SBI Clerk. MICA's official admissions page provides a 2027 calendar; the remaining records are marked pending unless their authorities publish a complete 2027 schedule. This prevents false precision while keeping every page ready for a future verified update."), table([["Record", "Current handling"], ["MICAT", "Published 2027 MICAT I and II dates copied from MICA's official admissions page."], ["AEEE, CG Pre MCA, CULEE, GEEE, GITAM GAT", "2027 schedule pending; official admission sources linked."], ["Haryana LEET, NMAT, OJEE, SBI Clerk", "2027 schedule pending; official board, GMAC or SBI source linked."], ["Related sessions", "JEE Main Session 2 and BITSAT Session 1/2 excluded from this batch to prevent duplicate intent."]], [45 * mm, 127 * mm]), H("Appendix B. Reusable author prompt skeleton", 1), P("You are a veteran education journalist and senior SEO content strategist. Write for Indian students and parents. Answer the intent in the first two or three sentences. Use official sources only, label pending information, include a comparison or summary table only when it helps the decision, four to eight distinct FAQs in the separate faqs field, four verified internal links, one official application link and one official notification link. Do not repeat FAQs inside article_html. Keep metadata within 60/155 characters, avoid forbidden phrases and do not invent experience, quotes, dates, prices, rankings, approvals or outcomes. Return strict structured fields: title, slug, description, article_html, meta_title, meta_description, meta_keywords, tags, category, hero_hook and faqs. Article HTML must not contain H1.")]

doc = SimpleDocTemplate(str(OUT), pagesize=A4, rightMargin=18 * mm, leftMargin=18 * mm, topMargin=22 * mm, bottomMargin=20 * mm, title="DekhoCampus Content Quality Playbook", author="DekhoCampus")
doc.build(story, onFirstPage=header_footer, onLaterPages=header_footer)
print(OUT)
