// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { apiBaseUrl, backendFetch, invokeNodeFunction } from '@/lib/backendMode';
import { normalizeJsonRequestBody } from '@/lib/typography';

const resolvedApiUrl = apiBaseUrl();
const localClientKey = 'dc-node-client';
export const supabaseProjectUrl = resolvedApiUrl;
const mediaBaseUrl = String(import.meta.env.VITE_MEDIA_BASE_URL || '').replace(/\/$/, '');

function createNodeFetch(): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (headers.get('Authorization') === `Bearer ${localClientKey}`) {
      headers.delete('Authorization');
    }
    return backendFetch(input, {
      ...init,
      body: normalizeJsonRequestBody(init?.body),
      headers,
    });
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// The existing UI keeps the Supabase query-builder API as a compatibility
// surface, but every request is now sent only to our Node API.
const supabaseClient = createClient<Database>(resolvedApiUrl, localClientKey, {
  global: {
    fetch: createNodeFetch(),
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

const encodeObjectPath = (value: string) => value.split('/').map(encodeURIComponent).join('/');

async function storageHeaders(extra?: HeadersInit) {
  const headers = new Headers(extra);
  const { data: { session } } = await supabaseClient.auth.getSession();
  if (session?.access_token) headers.set('authorization', `Bearer ${session.access_token}`);
  return headers;
}

async function storageJson(response: Response) {
  const payload = await response.json().catch(() => null);
  if (!response.ok) return { data: null, error: new Error(payload?.message || payload?.error || `Storage returned ${response.status}`) };
  return { data: payload, error: null };
}

// Preserve the storage API used throughout the UI while Node authorizes S3
// mutations and CloudFront serves public media directly.
const storageCompatibility = {
  from(bucket: string) {
    const bucketPath = encodeURIComponent(bucket);
    return {
      async upload(path: string, body: Blob | ArrayBuffer | Uint8Array, options: { upsert?: boolean; contentType?: string; cacheControl?: string } = {}) {
        const headers = await storageHeaders({
          'content-type': options.contentType || (body instanceof Blob ? body.type : '') || 'application/octet-stream',
          'x-upsert': String(Boolean(options.upsert)),
          ...(options.cacheControl ? { 'cache-control': options.cacheControl } : {}),
        });
        return storageJson(await fetch(`${resolvedApiUrl}/storage/v1/object/${bucketPath}/${encodeObjectPath(path)}`, { method: 'POST', headers, body: body as BodyInit }));
      },
      async update(path: string, body: Blob | ArrayBuffer | Uint8Array, options: { contentType?: string; cacheControl?: string } = {}) {
        const headers = await storageHeaders({
          'content-type': options.contentType || (body instanceof Blob ? body.type : '') || 'application/octet-stream',
          'x-upsert': 'true',
          ...(options.cacheControl ? { 'cache-control': options.cacheControl } : {}),
        });
        return storageJson(await fetch(`${resolvedApiUrl}/storage/v1/object/${bucketPath}/${encodeObjectPath(path)}`, { method: 'PUT', headers, body: body as BodyInit }));
      },
      async list(prefix = '', options: { limit?: number; offset?: number; sortBy?: { column?: string; order?: string } } = {}) {
        const headers = await storageHeaders({ 'content-type': 'application/json' });
        return storageJson(await fetch(`${resolvedApiUrl}/storage/v1/object/list/${bucketPath}`, {
          method: 'POST', headers, body: JSON.stringify({ prefix, limit: options.limit || 100, offset: options.offset || 0, sortBy: options.sortBy }),
        }));
      },
      async remove(paths: string[]) {
        const headers = await storageHeaders({ 'content-type': 'application/json' });
        return storageJson(await fetch(`${resolvedApiUrl}/storage/v1/object/${bucketPath}`, { method: 'DELETE', headers, body: JSON.stringify({ prefixes: paths }) }));
      },
      getPublicUrl(path: string) {
        return { data: { publicUrl: `${mediaBaseUrl}/${encodeURIComponent(bucket)}/${encodeObjectPath(path)}` } };
      },
      async createSignedUrl(path: string, expiresIn: number) {
        const headers = await storageHeaders({ 'content-type': 'application/json' });
        return storageJson(await fetch(`${resolvedApiUrl}/storage/v1/object/sign/${bucketPath}/${encodeObjectPath(path)}`, { method: 'POST', headers, body: JSON.stringify({ expiresIn }) }));
      },
      async download(path: string) {
        const headers = await storageHeaders();
        const response = await fetch(`${resolvedApiUrl}/storage/v1/object/authenticated/${bucketPath}/${encodeObjectPath(path)}`, { headers });
        if (!response.ok) return { data: null, error: new Error(`Storage returned ${response.status}`) };
        return { data: await response.blob(), error: null };
      },
    };
  },
};

export const supabase = new Proxy(supabaseClient, {
  get(target, property, receiver) {
    if (property === 'storage') return storageCompatibility;
    if (property === 'functions') {
      return new Proxy(target.functions, {
        get(functions, functionProperty, functionReceiver) {
          if (functionProperty === 'invoke') {
            return async (name: string, options: { body?: unknown; headers?: HeadersInit; method?: string } = {}) => {
              const { data: { session } } = await target.auth.getSession();
              const headers = new Headers(options.headers);
              if (session?.access_token) headers.set('authorization', `Bearer ${session.access_token}`);
              return invokeNodeFunction(name, { ...options, headers });
            };
          }
          return Reflect.get(functions, functionProperty, functionReceiver);
        },
      });
    }
    return Reflect.get(target, property, receiver);
  },
}) as typeof supabaseClient;
