// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { backendFetch, backendTarget, invokeNodeFunction } from '@/lib/backendMode';
import { normalizeJsonRequestBody } from '@/lib/typography';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const FALLBACK_SUPABASE_URL = 'https://kozdctbbvrnyddlftmvf.supabase.co';
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_XeGGxsGIdsWpU0u3L3xSTg_I775axzd';

const resolvedSupabaseUrl =
  typeof SUPABASE_URL === 'string' && SUPABASE_URL.trim()
    ? SUPABASE_URL.trim()
    : FALLBACK_SUPABASE_URL;

export const supabaseProjectUrl = resolvedSupabaseUrl.replace(/\/$/, '');

const resolvedSupabaseKey =
  typeof SUPABASE_PUBLISHABLE_KEY === 'string' &&
  SUPABASE_PUBLISHABLE_KEY.trim() &&
  !SUPABASE_PUBLISHABLE_KEY.startsWith('sb_secret_')
    ? SUPABASE_PUBLISHABLE_KEY.trim()
    : FALLBACK_SUPABASE_PUBLISHABLE_KEY;

if (typeof SUPABASE_PUBLISHABLE_KEY === 'string' && SUPABASE_PUBLISHABLE_KEY.startsWith('sb_secret_')) {
  console.error(
    'VITE_SUPABASE_PUBLISHABLE_KEY is configured with a secret key. Using the public publishable fallback to avoid a blank site. Fix the production env variable.',
  );
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return backendFetch(input, {
      ...init,
      body: normalizeJsonRequestBody(init?.body),
      headers,
    });
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const supabaseClient = createClient<Database>(resolvedSupabaseUrl, resolvedSupabaseKey, {
  global: {
    fetch: createSupabaseFetch(resolvedSupabaseKey),
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Existing code calls `supabase.functions.invoke(...)`. Intercept that single
// trigger point so every Edge Function gets the same two-switch behaviour.
// Database/Auth/Storage remain on Supabase until they are migrated separately.
export const supabase = new Proxy(supabaseClient, {
  get(target, property, receiver) {
    if (property === 'functions') {
      return new Proxy(target.functions, {
        get(functions, functionProperty, functionReceiver) {
          if (functionProperty === 'invoke') {
            return async (name: string, options: { body?: unknown; headers?: HeadersInit; method?: string } = {}) => {
              if (backendTarget() !== 'node') return target.functions.invoke(name, options as never);
              const { data: { session } } = await target.auth.getSession();
              const headers = new Headers(options.headers);
              headers.set('apikey', resolvedSupabaseKey);
              if (session?.access_token) headers.set('authorization', `Bearer ${session.access_token}`);
              return invokeNodeFunction(name, { ...options, headers });
            };
          }
          return Reflect.get(functions, functionProperty, functionReceiver);
        },
      });
    }
    return Reflect.get(target, property, receiver);
  },
}) as typeof supabaseClient;
