// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { apiBaseUrl, backendFetch, invokeNodeFunction } from '@/lib/backendMode';
import { normalizeJsonRequestBody } from '@/lib/typography';

const resolvedApiUrl = apiBaseUrl();
const localClientKey = 'dc-node-client';
export const supabaseProjectUrl = resolvedApiUrl;
const storageProjectUrl = String(import.meta.env.VITE_SUPABASE_STORAGE_URL || '').replace(/\/$/, '');

function createNodeFetch(): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (headers.get('Authorization') === `Bearer ${localClientKey}`) {
      headers.delete('Authorization');
    }
    return backendFetch(input, {
      ...init,
      body: normalizeJsonRequestBody(init?.body),
      headers,
    });
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// The existing UI keeps the Supabase query-builder API as a compatibility
// surface, but every request is now sent only to our Node API.
const supabaseClient = createClient<Database>(resolvedApiUrl, localClientKey, {
  global: {
    fetch: createNodeFetch(),
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Storage keeps using Supabase, while credentials and authorization stay on
// the Node side. Storage mutations are sent through Node; generated public
// URLs point directly at Supabase's CDN.
const storageClient = storageProjectUrl
  ? createClient<Database>(storageProjectUrl, 'dc-storage-proxy', {
      global: {
        fetch: async (input, init) => {
          const original = typeof input === 'string'
            ? input
            : input instanceof URL
              ? input.toString()
              : input.url;
          const url = new URL(original);
          const headers = new Headers(
            typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
          );
          if (init?.headers) new Headers(init.headers).forEach((value, key) => headers.set(key, value));
          const { data: { session } } = await supabaseClient.auth.getSession();
          if (session?.access_token) headers.set('authorization', `Bearer ${session.access_token}`);
          else headers.delete('authorization');

          if (url.pathname.startsWith('/storage/v1/')) {
            return fetch(`${resolvedApiUrl}${url.pathname}${url.search}`, { ...init, headers });
          }
          return fetch(input, { ...init, headers });
        },
      },
      auth: { persistSession: false, autoRefreshToken: false },
    })
  : null;

export const supabase = new Proxy(supabaseClient, {
  get(target, property, receiver) {
    if (property === 'storage' && storageClient) return storageClient.storage;
    if (property === 'functions') {
      return new Proxy(target.functions, {
        get(functions, functionProperty, functionReceiver) {
          if (functionProperty === 'invoke') {
            return async (name: string, options: { body?: unknown; headers?: HeadersInit; method?: string } = {}) => {
              const { data: { session } } = await target.auth.getSession();
              const headers = new Headers(options.headers);
              if (session?.access_token) headers.set('authorization', `Bearer ${session.access_token}`);
              return invokeNodeFunction(name, { ...options, headers });
            };
          }
          return Reflect.get(functions, functionProperty, functionReceiver);
        },
      });
    }
    return Reflect.get(target, property, receiver);
  },
}) as typeof supabaseClient;
